import Link from 'next/link'
import { Mail, MessageSquare, ShieldAlert } from 'lucide-react'
import { SitePage, PolicySection } from '@/components/site-page'

export const metadata = { title: 'Contact Support | EO Finder', description: 'Get help with EO Finder, station reports, privacy, and account requests.' }

export default function ContactPage() {
  return <SitePage eyebrow="Support" title="Contact EO Finder Support" intro="We are here to help with app issues, station corrections, privacy questions, and account requests.">
    <div className="grid gap-4 sm:grid-cols-2"><a href="mailto:support@eofinder.app" className="flex flex-col gap-3 rounded-xl border border-border p-5 transition-colors hover:border-primary hover:bg-primary/[0.04]"><Mail className="text-primary" /><strong>Email support</strong><span className="text-sm leading-6 text-muted-foreground">support@eofinder.app<br />We aim to respond as soon as possible.</span></a><Link href="/delete-account" className="flex flex-col gap-3 rounded-xl border border-border p-5 transition-colors hover:border-primary hover:bg-primary/[0.04]"><ShieldAlert className="text-primary" /><strong>Delete your account</strong><span className="text-sm leading-6 text-muted-foreground">Request account and associated data deletion.</span></Link></div><div className="mt-8 flex flex-col gap-8"><PolicySection title="What to include"><p>For the fastest response, include your device model, app version, the station or feature involved, and a clear description of the issue. Do not send passwords, payment details, or other sensitive information.</p></PolicySection><PolicySection title="Station corrections"><p>Send the station name, location, incorrect detail, and any supporting context. Our team may review and update the listing.</p></PolicySection><PolicySection title="App feedback"><p>We welcome suggestions for better search, reporting, navigation, and accessibility. Email us with the subject “Feature feedback.”</p></PolicySection></div><div className="mt-8 flex items-center gap-3 rounded-xl bg-primary/[0.06] p-4 text-sm text-muted-foreground"><MessageSquare className="shrink-0 text-primary" /> Support is currently handled by email so every request can be tracked.</div>
  </SitePage>
}
