import { SitePage, PolicySection, BulletList } from '@/components/site-page'

export const metadata = { title: 'Privacy Policy — E0 Finder', description: 'Privacy Policy for the E0 Finder mobile application and website.' }

export default function PrivacyPage() {
  return <SitePage eyebrow="Legal" title="Privacy Policy" intro="Last updated: August 14, 2026. This policy explains how E0 Finder collects, uses, and protects information when you use our app or website.">
    <div className="flex flex-col gap-8"><PolicySection title="Information we collect"><p>We may collect information you provide, such as your name, email address, profile details, station reports, and support messages.</p><p>When you use location features, we may process your device location to show nearby petrol stations. You can disable location permission in your device settings.</p><p>We may also collect basic device, log, and usage information to keep the service secure and improve reliability.</p></PolicySection><PolicySection title="How we use information"><BulletList items={['Provide station search, maps, directions, favorites, and reporting features.', 'Verify, moderate, and improve community-submitted station information.', 'Respond to support requests and communicate important service updates.', 'Detect abuse, protect users, and maintain the security of our systems.', 'Understand usage trends and improve the app experience.']} /></PolicySection><PolicySection title="Sharing and disclosure"><p>We do not sell personal information. We may share information with service providers that help us host, secure, analyze, or operate the service, subject to appropriate safeguards.</p><p>We may disclose information when required by law, to protect rights and safety, or as part of a business transfer.</p></PolicySection><PolicySection title="Data retention and security"><p>We retain information only as long as reasonably necessary for the purposes described here, legal obligations, dispute resolution, and security. We use reasonable technical and organizational safeguards, but no online service can guarantee absolute security.</p></PolicySection><PolicySection title="Your choices and rights"><p>You may request access, correction, or deletion of your personal information by contacting us. You may withdraw location permission or stop using the app at any time. Some information may be retained when legally required or needed for security.</p></PolicySection><PolicySection title="Children’s privacy"><p>E0 Finder is not directed to children under 13. We do not knowingly collect personal information from children under 13.</p></PolicySection><PolicySection title="Contact"><p>Questions about privacy can be sent to <a className="font-semibold text-primary hover:underline" href="mailto:support@e0-finder.app">support@e0-finder.app</a>.</p></PolicySection></div>
  </SitePage>
}
