'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, ExternalLink, Fuel, Camera, Menu, Navigation, Search, ShieldCheck, Smartphone, Users, Video, X, Zap } from 'lucide-react'

const sourceImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2014%2C%202026%2C%2011_03_09%20AM-bFhvU8Bf9QJVtBtKsMpARpzV40boX0.png'
const playStoreUrl = 'https://play.google.com/store/apps/details?id=com.anupampradhan.ethanolfreepetrol'
const navItems = [['Features', 'features'], ['How It Works', 'how-it-works'], ['Why EO', 'why-eo'], ['Screenshots', 'screenshots'], ['FAQ', 'faq'], ['About Us', 'about-us'], ['Contact', 'contact']]
const benefits = [{ icon: Fuel, title: '0% Ethanol', text: 'EO Petrol Only' }, { icon: ShieldCheck, title: 'Verified Stations', text: 'Team & community verified' }, { icon: Zap, title: 'Live Availability', text: 'Real-time station updates' }, { icon: Users, title: 'Community Driven', text: 'Trusted by 10K+ users' }]
const steps = [{ icon: Search, title: 'Search', text: 'Search any city, area or petrol station.' }, { icon: Fuel, title: 'Check EO Status', text: 'View 0% ethanol availability in real-time.' }, { icon: Navigation, title: 'Navigate', text: 'Get directions to the verified EO station.' }, { icon: Users, title: 'Report & Help', text: 'Add reports and help the community.' }]
const faqs = [['What is EO Finder?', 'EO Finder helps you discover verified petrol stations offering ethanol-free, 0% ethanol fuel.'], ['How is station information verified?', 'Station information comes from our verification team and community reports, with live availability updates wherever possible.'], ['Is EO Finder free to use?', 'Yes. The app is designed to help drivers find better fuel options without a subscription.'], ['How can I report a station update?', 'Use the Add Report flow in the app to share fuel type, availability, and station details with the community.']]

function Logo() { return <a href="#home" className="flex items-center gap-3" aria-label="EO Finder home"><span className="grid size-11 place-items-center rounded-xl bg-primary text-lg font-black text-primary-foreground shadow-sm">E0</span><span><strong className="block text-2xl leading-none tracking-tight">Finder</strong><small className="text-xs text-muted-foreground">Find Ethanol-Free Petrol</small></span></a> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <main id="home" className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6 px-5 py-3 lg:px-8"><Logo /><nav className="hidden items-center gap-7 lg:flex">{navItems.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)} className="text-sm font-semibold text-foreground/80 transition-colors hover:text-primary">{label}</button>)}</nav><div className="flex items-center gap-3"><a href={playStoreUrl} target="_blank" rel="noreferrer" className="hidden items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:scale-[1.02] sm:flex">Get it on Google Play <ExternalLink size={16} /></a><button className="rounded-lg p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <nav className="flex flex-col gap-1 border-t border-border px-5 py-4 lg:hidden">{[['Home', 'home'], ...navItems].map(([label, id]) => <button key={id} className="rounded-md px-3 py-2 text-left font-semibold hover:bg-muted" onClick={() => scrollTo(id)}>{label}</button>)}</nav>}</header>
    <section className="mx-auto grid max-w-7xl items-center gap-8 px-5 pb-12 pt-12 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:pb-16 lg:pt-16"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.2em] text-primary">Fuel smarter. Drive better.</p><h1 className="max-w-2xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl">Find <span className="text-primary">0% Ethanol</span> Petrol Stations Near You</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">EO Finder helps you find verified ethanol-free petrol stations in real-time. Better performance, more mileage, ideal for your engine.</p><div className="mt-8 grid max-w-xl grid-cols-2 gap-5 sm:grid-cols-4">{benefits.map(({ icon: Icon, title, text }) => <div key={title} className="flex flex-col gap-2"><span className="grid size-12 place-items-center rounded-full bg-primary/10 text-primary"><Icon /></span><strong className="text-sm">{title}</strong><span className="text-xs leading-5 text-muted-foreground">{text}</span></div>)}</div><div className="mt-9 flex flex-wrap gap-4"><a href={playStoreUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3.5 font-semibold text-primary-foreground shadow-sm">Get it on Google Play <ExternalLink size={17} /></a><button onClick={() => scrollTo('how-it-works')} className="inline-flex items-center gap-2 rounded-lg border border-border bg-background px-6 py-3.5 font-semibold hover:border-primary hover:text-primary">Learn More <ArrowRight size={17} /></button></div></div><div className="relative min-h-[330px] overflow-hidden rounded-2xl lg:min-h-[520px]"><img src={sourceImage} alt="EO Finder app showing verified petrol stations" className="absolute inset-0 size-full object-cover object-right" /><div className="absolute inset-0 bg-gradient-to-r from-background/80 via-transparent to-transparent" /><div className="absolute bottom-7 left-5 flex items-center gap-3 rounded-2xl bg-background/95 px-5 py-4 shadow-xl sm:left-10"><ShieldCheck className="text-primary" /><div><strong className="block text-lg text-primary">100% EO</strong><span className="text-sm font-semibold">Verified Stations</span></div></div></div></section>
    <section id="features" className="border-y border-primary/10 bg-primary/[0.04]"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-6 sm:grid-cols-3 lg:px-8">{[['100% EO Verified', 'Only 0% ethanol petrol stations'], ['10K+ Users', 'Community trusted & growing'], ['Real-time Updates', 'Live availability & price updates']].map(([title, text], i) => <div key={title} className="flex items-center gap-4 border-border sm:border-r sm:px-6 first:sm:pl-0 last:sm:border-0"><span className="text-primary">{i === 0 ? <ShieldCheck size={32} /> : i === 1 ? <Users size={32} /> : <Zap size={32} />}</span><div><strong className="block">{title}</strong><span className="text-sm text-muted-foreground">{text}</span></div></div>)}</div></section>
    <section id="how-it-works" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[0.75fr_1.25fr] lg:px-8"><div><p className="mb-2 text-sm font-bold uppercase tracking-widest text-primary">Simple by design</p><h2 className="text-3xl font-black sm:text-4xl">How <span className="text-primary">EO Finder</span> Works?</h2><div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-1">{steps.map(({ icon: Icon, title, text }, i) => <div key={title} className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Icon /></span><div><strong className="block">{i + 1}. {title}</strong><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></div><div id="screenshots" className="overflow-hidden rounded-2xl border border-border bg-muted/30"><div className="flex items-center justify-between border-b border-border px-6 py-4"><h2 className="text-2xl font-black">App Screenshots</h2><Smartphone className="text-primary" /></div><img src={sourceImage} alt="EO Finder mobile app screens" className="h-[390px] w-full object-cover object-left-bottom" /></div></section>
    <section id="why-eo" className="bg-primary py-16 text-primary-foreground"><div className="mx-auto max-w-4xl px-5 text-center"><p className="text-sm font-bold uppercase tracking-widest text-primary-foreground/75">Why choose EO?</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Better fuel starts with better information.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-primary-foreground/80">Find fuel that is kinder to your engine, make informed decisions on the road, and contribute to a trusted community of drivers.</p><div className="mt-8 flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm font-semibold">{['Verified listings', 'Live updates', 'Community reports', 'Easy navigation'].map((item) => <span key={item} className="inline-flex items-center gap-2"><Check size={17} /> {item}</span>)}</div></div></section>
    <section id="faq" className="mx-auto max-w-3xl px-5 py-16"><p className="text-center text-sm font-bold uppercase tracking-widest text-primary">Questions answered</p><h2 className="mt-2 text-center text-3xl font-black">Frequently Asked Questions</h2><div className="mt-8 flex flex-col gap-3">{faqs.map(([question, answer], i) => <div key={question} className="rounded-xl border border-border"><button className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left font-bold" onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i}>{question}<ChevronDown className={openFaq === i ? 'rotate-180 text-primary transition-transform' : 'transition-transform'} /></button>{openFaq === i && <p className="px-5 pb-5 leading-7 text-muted-foreground">{answer}</p>}</div>)}</div></section>
    <section id="about-us" className="mx-auto max-w-7xl border-t border-border px-5 py-14 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-primary">About EO Finder</p><h2 className="mt-2 text-3xl font-black">Built for drivers who care about their engines.</h2><p className="mt-5 leading-7 text-muted-foreground">EO Finder makes it easier to locate ethanol-free petrol and share reliable station information. Our mission is to make every trip more informed, efficient, and engine-friendly.</p></div></section>
    <section id="contact" className="mx-auto mb-16 flex max-w-7xl flex-col items-center justify-between gap-6 rounded-xl border border-primary/15 bg-primary/[0.04] px-6 py-8 text-center sm:flex-row sm:text-left lg:px-10"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-xl bg-primary/10 text-primary"><Smartphone /></span><div><h2 className="text-2xl font-black">Start Using <span className="text-primary">EO Finder</span> Today!</h2><p className="text-muted-foreground">Download the app and find ethanol-free petrol stations near you.</p></div></div><a href="mailto:support@e0-finder.app" className="rounded-lg border border-primary px-5 py-3 font-semibold text-primary hover:bg-primary hover:text-primary-foreground">Contact Support</a></section>
    <footer className="bg-primary py-8 text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 lg:px-8"><div className="flex flex-col items-center justify-between gap-5 sm:flex-row"><div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-primary-foreground text-sm font-bold text-primary">E0</span><strong className="text-xl">Finder</strong></div><p className="mt-2 text-xs text-primary-foreground/70">Find Ethanol-Free Petrol Stations</p></div><div className="flex flex-wrap justify-center gap-x-5 gap-y-2 text-sm text-primary-foreground/85"><a href="/privacy" className="hover:underline">Privacy Policy</a><a href="/terms" className="hover:underline">Terms of Use</a><a href="/disclaimer" className="hover:underline">Disclaimer</a><a href="/contact" className="hover:underline">Contact Us</a><a href="/delete-account" className="hover:underline">Delete Account</a></div><div className="flex gap-3" aria-label="Social links"><a href="https://instagram.com" aria-label="Instagram"><Camera /></a><a href="https://youtube.com" aria-label="YouTube"><Video /></a><a href={playStoreUrl} aria-label="Google Play"><ExternalLink /></a></div></div><div className="border-t border-primary-foreground/20 pt-5 text-center text-xs text-primary-foreground/65">© 2026 EO Finder. All rights reserved. <span id="privacy">Privacy policy available on request.</span> <span id="terms">Terms apply.</span> <span id="disclaimer">Information may change based on community updates.</span></div></div></footer>
  </main>
}
