import { Mail } from 'lucide-react'
import { SitePage, PolicySection, BulletList } from '@/components/site-page'

export const metadata = { title: 'Delete Account | EO Finder', description: 'Request deletion of your EO Finder account and associated personal data.' }

export default function DeleteAccountPage() {
  return <SitePage eyebrow="Account management" title="Delete your EO Finder account" intro="You can request deletion of your EO Finder account and associated personal information by contacting support.">
    <div className="flex flex-col gap-8"><div className="rounded-xl bg-primary/[0.06] p-5"><p className="font-semibold">Email <a className="text-primary hover:underline" href="mailto:support@eofinder.app?subject=Delete%20my%20EO%20Finder%20account">support@eofinder.app</a> with the subject “Delete my EO Finder account.”</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Please send the request from the email address associated with your account where possible so we can verify ownership.</p></div><PolicySection title="What will be deleted"><BulletList items={['Your account profile and account identifiers.', 'Saved preferences and favorites associated with your account.', 'Personal information held for operating the service.']} /></PolicySection><PolicySection title="What may be retained"><p>We may retain limited information when necessary for legal compliance, fraud prevention, security, dispute resolution, or records that have been anonymized and no longer identify you.</p></PolicySection><PolicySection title="Processing"><p>We may ask for reasonable verification before completing a deletion request. Once verified, we will process the request within a reasonable period and confirm by email. Deleting your account may not remove reports that have been made anonymous or are needed to preserve the integrity of station information.</p></PolicySection><PolicySection title="Need help?"><p>For questions about deletion or privacy, email <a className="font-semibold text-primary hover:underline" href="mailto:support@eofinder.app">support@eofinder.app</a>.</p></PolicySection><a href="mailto:support@eofinder.app?subject=Delete%20my%20EO%20Finder%20account" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3 font-semibold text-primary-foreground hover:opacity-90"><Mail size={17} /> Request account deletion</a></div>
  </SitePage>
}
