import { SitePage, PolicySection, BulletList } from '@/components/site-page'

export const metadata = { title: 'Terms of Use | EO Finder', description: 'Terms of Use for EO Finder.' }

export default function TermsPage() {
  return <SitePage eyebrow="Legal" title="Terms of Use" intro="Last updated: August 14, 2026. By using EO Finder, you agree to these terms. If you do not agree, do not use the service.">
    <div className="flex flex-col gap-8"><PolicySection title="The service"><p>EO Finder provides tools to discover, review, and share information about petrol stations and fuel availability. Features may change, be interrupted, or become unavailable.</p></PolicySection><PolicySection title="Information accuracy"><p>Station listings, prices, opening hours, availability, directions, and community reports may be incomplete, delayed, or inaccurate. Always confirm fuel availability and local conditions before relying on information.</p></PolicySection><PolicySection title="Acceptable use"><BulletList items={['Use the service lawfully and respectfully.', 'Do not submit false, misleading, abusive, or unlawful content.', 'Do not interfere with, reverse engineer, scrape, or overload the service.', 'Do not attempt to access accounts, systems, or data without authorization.']} /></PolicySection><PolicySection title="User content"><p>You are responsible for reports and other content you submit. You grant EO Finder a non-exclusive, worldwide, royalty-free license to host, display, reproduce, and use that content to operate and improve the service. We may remove content that violates these terms.</p></PolicySection><PolicySection title="Third-party services"><p>The app may link to maps, navigation, app stores, or other third-party services. Their terms and privacy policies apply separately. EO Finder is not responsible for third-party services.</p></PolicySection><PolicySection title="Disclaimer and liability"><p>The service is provided on an “as available” basis. To the extent permitted by law, EO Finder is not liable for indirect losses, fuel decisions, route changes, inaccurate listings, or service interruptions.</p></PolicySection><PolicySection title="Changes and contact"><p>We may update these terms by posting a revised version. Continued use after changes means you accept the updated terms. Contact <a className="font-semibold text-primary hover:underline" href="mailto:support@eofinder.app">support@eofinder.app</a> with questions.</p></PolicySection></div>
  </SitePage>
}
