export interface WebStation {
  id: string
  name: string
  brand: 'IndianOil' | 'HPCL' | 'BPCL' | 'Shell' | 'Jio-bp'
  brandLogo: string
  fuelGrade: 'XP100 (0% Ethanol)' | 'poWer100 (0% Ethanol)' | 'Speed 97 (0% Ethanol)' | 'Verified E0 Batch'
  isE0Confirmed: boolean
  isCOCO: boolean
  address: string
  area: string
  city: string
  state: string
  pincode: string
  latitude: number
  longitude: number
  price: number
  density: string
  lastVerified: string
  verifiedBy: string
  rating: number
  reviewCount: number
  isOpen24Hours: boolean
  timing: string
  phone: string
  amenities: string[]
}

export const initialStations: WebStation[] = [
  // BENGALURU
  {
    id: 'iocl-coco-koramangala-blr',
    name: 'IndianOil COCO Auto Care Koramangala',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'No. 19/A, Block 6, 80 Feet Road, Koramangala, Bengaluru',
    area: 'Koramangala 6th Block',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560095',
    latitude: 12.9348,
    longitude: 77.6205,
    price: 145.0,
    density: '734.8 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'IndianOil ONE App & Form-8 Density Log',
    rating: 4.9,
    reviewCount: 310,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 80 2553 4411',
    amenities: ['XP100 Dedicated Bay', 'Digital Nitrogen & Air', 'UPI / NFC / Cards', 'Clean Restrooms', 'EV Fast Charging'],
  },
  {
    id: 'iocl-coco-hebbal-blr',
    name: 'IndianOil COCO Auto Care Centre Hebbal',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Bellary Road, Near Hebbal Flyover Junction, Bengaluru',
    area: 'Hebbal / Airport Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560024',
    latitude: 13.0358,
    longitude: 77.597,
    price: 145.0,
    density: '735.2 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Hydrometer Purity Inspection',
    rating: 4.9,
    reviewCount: 220,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 80 2341 5500',
    amenities: ['XP100 Dispenser', 'KIA Airport Access', 'Nitrogen Station', 'UPI / Credit Card', 'Car Wash'],
  },
  {
    id: 'hpcl-auto-care-kodihalli-blr',
    name: 'HPCL Auto Care Centre Kodihalli',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Old Airport Road, Kodihalli, Bengaluru',
    area: 'Indiranagar / Domlur',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560008',
    latitude: 12.9601,
    longitude: 77.6484,
    price: 146.0,
    density: '736.0 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Superbike Community Verification',
    rating: 4.8,
    reviewCount: 140,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 80 2521 3322',
    amenities: ['poWer100 Dispenser', 'Digital Air', 'Club HP Pay', 'Clean Washrooms'],
  },

  // DELHI NCR
  {
    id: 'iocl-coco-niti-marg-del',
    name: 'IndianOil COCO Niti Marg Chanakyapuri',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Niti Marg, Diplomatic Enclave, Chanakyapuri, New Delhi',
    area: 'Chanakyapuri',
    city: 'Delhi NCR',
    state: 'Delhi',
    pincode: '110021',
    latitude: 28.5921,
    longitude: 77.195,
    price: 145.0,
    density: '734.5 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'Official IOCL XP100 Flagship Audit',
    rating: 5.0,
    reviewCount: 420,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 11 2410 8890',
    amenities: ['XP100 Dispenser', 'Digital Air & Nitrogen', 'Wheel Alignment', 'UPI & Cards', 'Convenience Store'],
  },
  {
    id: 'iocl-coco-jungpura-del',
    name: 'IndianOil COCO Jungpura',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Mathura Road, Near Jungpura Metro Station, New Delhi',
    area: 'Jungpura / Mathura Road',
    city: 'Delhi NCR',
    state: 'Delhi',
    pincode: '110014',
    latitude: 28.5835,
    longitude: 77.2458,
    price: 145.0,
    density: '735.0 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Form-8 Density Register Checked',
    rating: 4.9,
    reviewCount: 260,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 11 2437 2233',
    amenities: ['XP100 Dedicated Bay', 'Nitrogen', 'UPI / Card', 'Restroom'],
  },
  {
    id: 'hpcl-sec56-gurgaon',
    name: 'HPCL Auto Care Centre Sector 56 Gurgaon',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Golf Course Extension Road, Sector 56, Gurugram',
    area: 'Golf Course Extension Road',
    city: 'Delhi NCR',
    state: 'Haryana',
    pincode: '122011',
    latitude: 28.4239,
    longitude: 77.0988,
    price: 147.0,
    density: '736.8 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Team-BHP NCR Supercar Log',
    rating: 4.9,
    reviewCount: 195,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 124 257 8899',
    amenities: ['poWer100 Dispenser', 'Digital Air', 'Clean Restrooms', 'Credit Cards'],
  },
  {
    id: 'iocl-dnd-noida',
    name: 'IndianOil COCO Sector 16A Film City',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Sector 16A, Near DND Flyway Toll Plaza, Noida',
    area: 'Film City / DND Toll',
    city: 'Delhi NCR',
    state: 'Uttar Pradesh',
    pincode: '201301',
    latitude: 28.5714,
    longitude: 77.3142,
    price: 144.5,
    density: '734.0 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'DND Expressway Daily Patrol Log',
    rating: 4.8,
    reviewCount: 210,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 120 251 4455',
    amenities: ['XP100 Dispenser', 'Expressway Toll Access', 'Nitrogen', 'UPI'],
  },

  // MUMBAI
  {
    id: 'iocl-coco-bkc-mumbai',
    name: 'IndianOil COCO Bandra Kurla Complex',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'BN Bhavan, Near MCA Club, BKC, Bandra East, Mumbai',
    area: 'Bandra Kurla Complex (BKC)',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    latitude: 19.0665,
    longitude: 72.868,
    price: 146.0,
    density: '735.4 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'IndianOil BKC Flagship Inspection',
    rating: 4.9,
    reviewCount: 380,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 22 2659 7788',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'UPI / Credit Card', 'EV Fast Charging', 'Cafe'],
  },
  {
    id: 'bpcl-coco-bandra-reclamation-mumbai',
    name: 'BPCL Company COCO Bandra Reclamation',
    brand: 'BPCL',
    brandLogo: '/assets/oil_company_logo/Bharat_Petroleum_logo.svg',
    fuelGrade: 'Speed 97 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Bandra Reclamation, Near Bandra-Worli Sea Link Toll, Mumbai',
    area: 'Bandra West / Sea Link',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    latitude: 19.0435,
    longitude: 72.833,
    price: 138.0,
    density: '737.5 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Sea Link Superbike Ride Log',
    rating: 4.9,
    reviewCount: 340,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 22 2640 1122',
    amenities: ['Speed 97 Dedicated Bay', 'Sea Link Approach', 'Nitrogen', 'UPI'],
  },
  {
    id: 'iocl-coco-cumballa-hill-mumbai',
    name: 'IndianOil Top Gear Auto Care Cumballa Hill',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'August Kranti Marg, Cumballa Hill, South Mumbai',
    area: 'Cumballa Hill / Pedder Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400026',
    latitude: 18.9662,
    longitude: 72.8095,
    price: 146.0,
    density: '735.0 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'South Mumbai Classic Car Club',
    rating: 5.0,
    reviewCount: 290,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 22 2380 4422',
    amenities: ['XP100 Dispenser', 'Nitrogen', 'UPI & Cards', 'Clean Restrooms'],
  },

  // PUNE
  {
    id: 'iocl-coco-sb-road-pune',
    name: 'IndianOil COCO Senapati Bapat Road',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Senapati Bapat Road, Near ICC Trade Tower, Pune',
    area: 'Shivajinagar / SB Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411016',
    latitude: 18.5362,
    longitude: 73.8301,
    price: 145.5,
    density: '736.0 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Pune Biking Community Audit',
    rating: 4.9,
    reviewCount: 230,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 20 2565 7788',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'UPI', 'Car Care'],
  },
  {
    id: 'hpcl-baner-pashan-pune',
    name: 'HPCL Auto Care Baner-Pashan Link Road',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: false,
    address: 'Baner-Pashan Link Road, Near Highway Exit, Baner, Pune',
    area: 'Baner / Mumbai Highway',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    latitude: 18.5529,
    longitude: 73.7932,
    price: 146.0,
    density: '737.1 kg/m³ @ 15°C',
    lastVerified: '5 hours ago',
    verifiedBy: 'Form-8 Register Verified',
    rating: 4.7,
    reviewCount: 160,
    isOpen24Hours: false,
    timing: '6:00 AM - 11:30 PM',
    phone: '+91 20 2729 4433',
    amenities: ['poWer100 Dispenser', 'Air & Water', 'UPI Payments'],
  },

  // HYDERABAD
  {
    id: 'iocl-coco-jubilee-hills-hyd',
    name: 'IndianOil COCO Jubilee Hills Outpost',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Road No. 36, Near Peddamma Temple, Jubilee Hills, Hyderabad',
    area: 'Jubilee Hills / Hitec City',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    latitude: 17.4319,
    longitude: 78.4072,
    price: 145.0,
    density: '735.8 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'Hydrometer Audit & Density Check',
    rating: 5.0,
    reviewCount: 310,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 40 2355 1100',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'Clean Restrooms', 'UPI & Cards'],
  },

  // CHENNAI
  {
    id: 'iocl-coco-ecr-chennai',
    name: 'IndianOil COCO Outpost East Coast Road',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'East Coast Road (ECR), Kottivakkam, Chennai',
    area: 'ECR / Thiruvanmiyur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600041',
    latitude: 12.9667,
    longitude: 80.2589,
    price: 144.0,
    density: '734.2 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Coastal Highway Rider Log',
    rating: 4.9,
    reviewCount: 225,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 44 2448 3344',
    amenities: ['XP100 Dispenser', 'ECR Highway Access', 'Nitrogen', 'UPI'],
  },

  // KOLKATA
  {
    id: 'iocl-coco-em-bypass-kolkata',
    name: 'IndianOil COCO Outlet EM Bypass',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Eastern Metropolitan Bypass, Near Ruby Hospital, Kasba, Kolkata',
    area: 'EM Bypass / Kasba',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700107',
    latitude: 22.5126,
    longitude: 88.3995,
    price: 145.0,
    density: '735.4 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Kolkata Supercar Community Log',
    rating: 4.8,
    reviewCount: 185,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 33 2442 8877',
    amenities: ['XP100 Dispenser', 'Digital Air', 'UPI', 'Restrooms'],
  },

  // CHANDIGARH
  {
    id: 'iocl-coco-sector28-chandigarh',
    name: 'IndianOil COCO Outlet Madhya Marg',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Madhya Marg, Sector 28D, Chandigarh',
    area: 'Sector 28 / Madhya Marg',
    city: 'Chandigarh',
    state: 'Punjab / Haryana',
    pincode: '160028',
    latitude: 30.7225,
    longitude: 76.7995,
    price: 144.0,
    density: '736.5 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Himalayan Tourer Log',
    rating: 4.9,
    reviewCount: 190,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 172 265 4400',
    amenities: ['XP100 Dispenser', 'Shimla Highway Access', 'Nitrogen', 'UPI'],
  },

  // JAIPUR
  {
    id: 'iocl-coco-jln-marg-jaipur',
    name: 'IndianOil COCO Outpost JLN Marg',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Jawaharlal Nehru Marg, Near Jawahar Kala Kendra, Jaipur',
    area: 'JLN Marg / Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    latitude: 26.8624,
    longitude: 75.8118,
    price: 146.5,
    density: '737.0 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Form-8 Density Log',
    rating: 4.8,
    reviewCount: 165,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 141 270 5566',
    amenities: ['XP100 Dispenser', 'Air & Nitrogen', 'UPI', 'Cards'],
  },

  // AHMEDABAD
  {
    id: 'iocl-coco-sg-highway-ahmedabad',
    name: 'IndianOil COCO Station SG Highway',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Sarkhej - Gandhinagar Highway, Near Iscon Cross Road, Ahmedabad',
    area: 'SG Highway / Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    latitude: 23.0315,
    longitude: 72.5074,
    price: 144.5,
    density: '736.2 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Supercar Club Verification',
    rating: 4.9,
    reviewCount: 240,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 79 2686 1122',
    amenities: ['XP100 Dispenser', 'Digital Air', 'EV Fast Charging', 'UPI'],
  },

  // KOCHI
  {
    id: 'iocl-coco-kaloor-kochi',
    name: 'IndianOil COCO Centre Kaloor',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Kaloor - Kadavanthra Road, Ernakulam, Kochi',
    area: 'Kaloor / Kadavanthra',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682017',
    latitude: 9.9912,
    longitude: 76.2991,
    price: 145.5,
    density: '735.0 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Marine & Automotive Fuel Audit',
    rating: 4.9,
    reviewCount: 150,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 484 233 4455',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'UPI', 'Restrooms'],
  },

  // GOA
  {
    id: 'iocl-porvorim-goa',
    name: 'IndianOil Jubilee Bunk NH66 Porvorim',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'NH66 Mumbai-Goa Highway, Near Mall de Goa, Porvorim',
    area: 'Porvorim / North Goa',
    city: 'Goa',
    state: 'Goa',
    pincode: '403521',
    latitude: 15.5348,
    longitude: 73.829,
    price: 143.5,
    density: '734.8 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Community Touring Log',
    rating: 4.8,
    reviewCount: 195,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 832 241 5566',
    amenities: ['XP100 Dispenser', 'NH66 Access', 'Nitrogen', 'UPI'],
  },
]
