export interface WebStation {
  id: string
  name: string
  brand: 'IndianOil' | 'HPCL' | 'BPCL' | 'Shell' | 'Jio-bp'
  brandLogo: string
  fuelGrade: 'XP100 (0% Ethanol)' | 'poWer100 (0% Ethanol)' | 'Speed 97 (0% Ethanol)' | 'Verified E0 Batch'
  isE0Confirmed: boolean
  isCOCO: boolean
  address: string
  area: string
  city: string
  state: string
  pincode: string
  latitude: number
  longitude: number
  price: number
  density: string
  lastVerified: string
  verifiedBy: string
  rating: number
  reviewCount: number
  isOpen24Hours: boolean
  timing: string
  phone: string
  amenities: string[]
}

export const initialStations: WebStation[] = [
  {
    id: 'iocl-hebbal-blr',
    name: 'IndianOil COCO Auto Care Centre',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Bellary Road, Near Hebbal Flyover, Bengaluru',
    area: 'Hebbal / Airport Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560024',
    latitude: 13.0358,
    longitude: 77.597,
    price: 145.0,
    density: '734.5 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Field Inspection & Hydrometer Test',
    rating: 4.9,
    reviewCount: 142,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 80 2341 5500',
    amenities: ['XP100 Dispenser', 'Digital Air & Nitrogen', 'UPI / Credit Card', 'Clean Washroom', 'EV Fast Charger'],
  },
  {
    id: 'hpcl-old-airport-blr',
    name: 'HPCL Auto Care Centre Kodihalli',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Old Airport Road, Kodihalli, Bengaluru',
    area: 'Indiranagar / Domlur',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560008',
    latitude: 12.9601,
    longitude: 77.6484,
    price: 146.0,
    density: '736.0 kg/m³ @ 15°C',
    lastVerified: '5 hours ago',
    verifiedBy: 'Community Driver Log (Receipt #4920)',
    rating: 4.8,
    reviewCount: 98,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 80 2521 3322',
    amenities: ['poWer100 Dispenser', 'Nitrogen Station', 'UPI Payments', 'Club HP Rewards'],
  },
  {
    id: 'iocl-chanakyapuri-del',
    name: 'IndianOil COCO Auto Care Outpost',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Neeti Marg, Chanakyapuri, New Delhi',
    area: 'Chanakyapuri / Diplomatic Enclave',
    city: 'Delhi NCR',
    state: 'Delhi',
    pincode: '110021',
    latitude: 28.5921,
    longitude: 77.195,
    price: 145.0,
    density: '735.0 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'Form-8 Density Inspection',
    rating: 5.0,
    reviewCount: 230,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 11 2410 8890',
    amenities: ['XP100 Dispenser', 'Nitrogen', 'Wheel Alignment', 'UPI & Cards', 'Cafe'],
  },
  {
    id: 'hpcl-golf-course-gurgaon',
    name: 'HPCL Auto Care Centre Sector 56',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Golf Course Extension Road, Sector 56, Gurgaon',
    area: 'Golf Course Road',
    city: 'Delhi NCR',
    state: 'Haryana',
    pincode: '122011',
    latitude: 28.4239,
    longitude: 77.0988,
    price: 147.0,
    density: '737.5 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Superbike Club Verification',
    rating: 4.9,
    reviewCount: 165,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 124 257 8899',
    amenities: ['poWer100 Dispenser', 'Digital Air', 'Clean Restrooms', 'Credit Cards'],
  },
  {
    id: 'iocl-noida-filmcity',
    name: 'IndianOil Flagship Outlet Sector 16A',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Sector 16A, Near DND Flyway Toll Plaza, Noida',
    area: 'Film City / DND',
    city: 'Delhi NCR',
    state: 'Uttar Pradesh',
    pincode: '201301',
    latitude: 28.5714,
    longitude: 77.3142,
    price: 144.5,
    density: '734.0 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Form-8 Register Verified',
    rating: 4.8,
    reviewCount: 180,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 120 251 4455',
    amenities: ['XP100 Dispenser', 'DND Highway Access', 'Nitrogen', 'UPI'],
  },
  {
    id: 'bpcl-bandra-mumbai',
    name: 'BPCL Company COCO Bandra Reclamation',
    brand: 'BPCL',
    brandLogo: '/assets/oil_company_logo/Bharat_Petroleum_logo.svg',
    fuelGrade: 'Speed 97 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Bandra Reclamation, Near Sea Link Entry, Mumbai',
    area: 'Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    latitude: 19.0435,
    longitude: 72.833,
    price: 138.0,
    density: '738.0 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'Community Verification (Team-BHP)',
    rating: 4.9,
    reviewCount: 285,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 22 2640 1122',
    amenities: ['Speed 97', 'Sea Link Access', 'Nitrogen', 'UPI / Card'],
  },
  {
    id: 'iocl-worli-mumbai',
    name: 'IndianOil Jubilee Outlet Worli',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Dr. Annie Besant Road, Near Nehru Centre, Worli, Mumbai',
    area: 'Worli / South Mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400018',
    latitude: 18.9912,
    longitude: 72.8165,
    price: 146.0,
    density: '735.2 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Form-8 Density Log',
    rating: 4.9,
    reviewCount: 195,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 22 2493 5544',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'UPI', 'Air Pump'],
  },
  {
    id: 'iocl-sb-road-pune',
    name: 'IndianOil COCO Outlet Senapati Bapat Road',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Senapati Bapat Road, Near ICC Tech Park, Pune',
    area: 'Shivajinagar / SB Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411016',
    latitude: 18.5362,
    longitude: 73.8301,
    price: 145.5,
    density: '736.0 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Field Inspection',
    rating: 4.9,
    reviewCount: 178,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 20 2565 7788',
    amenities: ['XP100 Dispenser', 'Nitrogen', 'UPI', 'Car Care'],
  },
  {
    id: 'hpcl-baner-pune',
    name: 'HPCL Auto Care Baner-Pashan Link Road',
    brand: 'HPCL',
    brandLogo: '/assets/oil_company_logo/Hindustan_Petroleum_Logo.svg',
    fuelGrade: 'poWer100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: false,
    address: 'Baner-Pashan Link Road, Baner, Pune',
    area: 'Baner / Aundh',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    latitude: 18.5529,
    longitude: 73.7932,
    price: 146.0,
    density: '737.1 kg/m³ @ 15°C',
    lastVerified: '6 hours ago',
    verifiedBy: 'Community Report',
    rating: 4.7,
    reviewCount: 110,
    isOpen24Hours: false,
    timing: '6:00 AM - 11:30 PM',
    phone: '+91 20 2729 4433',
    amenities: ['poWer100 Dispenser', 'Air & Water', 'UPI Payments'],
  },
  {
    id: 'iocl-jubilee-hills-hyd',
    name: 'IndianOil COCO Jubilee Hills',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Road No. 36, Jubilee Hills, Hyderabad',
    area: 'Jubilee Hills / Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    latitude: 17.4319,
    longitude: 78.4072,
    price: 145.0,
    density: '735.8 kg/m³ @ 15°C',
    lastVerified: '1 hour ago',
    verifiedBy: 'Form-8 Register Verified',
    rating: 5.0,
    reviewCount: 220,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 40 2355 1100',
    amenities: ['XP100 Dispenser', 'Nitrogen', 'Clean Restroom', 'UPI & Cards'],
  },
  {
    id: 'iocl-ecr-chennai',
    name: 'IndianOil COCO Outpost East Coast Road',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'East Coast Road (ECR), Kottivakkam, Chennai',
    area: 'ECR / Thiruvanmiyur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600041',
    latitude: 12.9667,
    longitude: 80.2589,
    price: 144.0,
    density: '734.2 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Coastal Highway Rider Log',
    rating: 4.9,
    reviewCount: 160,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 44 2448 3344',
    amenities: ['XP100 Dispenser', 'ECR Highway Access', 'Nitrogen', 'UPI'],
  },
  {
    id: 'iocl-em-bypass-kolkata',
    name: 'IndianOil COCO Outlet EM Bypass',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Eastern Metropolitan Bypass, Near Ruby Hospital, Kolkata',
    area: 'EM Bypass / Kasba',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700107',
    latitude: 22.5126,
    longitude: 88.3995,
    price: 145.0,
    density: '735.4 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Hydrometer Audit',
    rating: 4.8,
    reviewCount: 140,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 33 2442 8877',
    amenities: ['XP100 Dispenser', 'Digital Air', 'UPI', 'Restrooms'],
  },
  {
    id: 'iocl-sector-28-chandigarh',
    name: 'IndianOil COCO Outlet Madhya Marg',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Madhya Marg, Sector 28D, Chandigarh',
    area: 'Sector 28 / Madhya Marg',
    city: 'Chandigarh',
    state: 'Punjab / Haryana',
    pincode: '160028',
    latitude: 30.7225,
    longitude: 76.7995,
    price: 144.0,
    density: '736.5 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Himalayan Tourer Log',
    rating: 4.9,
    reviewCount: 155,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 172 265 4400',
    amenities: ['XP100 Dispenser', 'Shimla Highway Access', 'Nitrogen', 'UPI'],
  },
  {
    id: 'iocl-jln-marg-jaipur',
    name: 'IndianOil COCO Outpost JLN Marg',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Jawaharlal Nehru Marg, Near JKK, Jaipur',
    area: 'JLN Marg / Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    latitude: 26.8624,
    longitude: 75.8118,
    price: 146.5,
    density: '737.0 kg/m³ @ 15°C',
    lastVerified: '5 hours ago',
    verifiedBy: 'Form-8 Density Log',
    rating: 4.8,
    reviewCount: 125,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 141 270 5566',
    amenities: ['XP100 Dispenser', 'Air & Nitrogen', 'UPI', 'Cards'],
  },
  {
    id: 'iocl-kaloor-kochi',
    name: 'IndianOil COCO Centre Kaloor',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'Kaloor - Kadavanthra Road, Ernakulam, Kochi',
    area: 'Kaloor / Kadavanthra',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682017',
    latitude: 9.9912,
    longitude: 76.2991,
    price: 145.5,
    density: '735.0 kg/m³ @ 15°C',
    lastVerified: '4 hours ago',
    verifiedBy: 'Marine & Automotive Fuel Audit',
    rating: 4.9,
    reviewCount: 130,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 484 233 4455',
    amenities: ['XP100 Dispenser', 'Digital Nitrogen', 'UPI', 'Restrooms'],
  },
  {
    id: 'iocl-sg-highway-ahmedabad',
    name: 'IndianOil COCO Station SG Highway',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'SG Highway, Near Iscon Cross Road, Ahmedabad',
    area: 'SG Highway / Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    latitude: 23.0315,
    longitude: 72.5074,
    price: 144.5,
    density: '736.2 kg/m³ @ 15°C',
    lastVerified: '2 hours ago',
    verifiedBy: 'Supercar Club Verification',
    rating: 4.9,
    reviewCount: 210,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 79 2686 1122',
    amenities: ['XP100 Dispenser', 'Digital Air', 'EV Fast Charging', 'UPI'],
  },
  {
    id: 'iocl-porvorim-goa',
    name: 'IndianOil Jubilee Bunk NH66 Porvorim',
    brand: 'IndianOil',
    brandLogo: '/assets/oil_company_logo/indian-oil-logo.svg',
    fuelGrade: 'XP100 (0% Ethanol)',
    isE0Confirmed: true,
    isCOCO: true,
    address: 'NH66 Highway, Near Mall de Goa, Porvorim, Goa',
    area: 'Porvorim / North Goa',
    city: 'Goa',
    state: 'Goa',
    pincode: '403521',
    latitude: 15.5348,
    longitude: 73.829,
    price: 143.5,
    density: '734.8 kg/m³ @ 15°C',
    lastVerified: '3 hours ago',
    verifiedBy: 'Community Touring Log',
    rating: 4.8,
    reviewCount: 145,
    isOpen24Hours: true,
    timing: 'Open 24 Hours',
    phone: '+91 832 241 5566',
    amenities: ['XP100 Dispenser', 'NH66 Access', 'Nitrogen', 'UPI'],
  },
]
